<%@LANGUAGE="VBSCRIPT" CODEPAGE="65001"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>
<style type="text/css">
body {
	background-color: #999;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	line-height: 2px;
	color: #000;
}
</style>
</head>

<body>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="600" bgcolor="#A4A4A4"><table width="700" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
        <td height="550" bgcolor="#CCCCCC"><p >&gt;&nbsp;P03316 </p>
          <p >MNRGFFNMLGRRPFPAPTAMWRPRRRRQAAPMPARNGLASQIQQLTTAVSALVIGQATRP </p>
          <p >QPPRPRPPPRQKKQAPKQPPKPKKPKTQEKKKKQPAKPKPGKRQRMALKLEADRLFDVKN </p>
          <p >EDGDVIGHALAMEGKVMKPLHVKGTIDHPVLSKLKFTKSSAYDMEFAQLPVNMRSEAFTY </p>
          <p >TSEHPEGFYNWHHGAVQYSGGRFTIPRGVGGRGDSGRPIMDNSGRVVAIVLGGADEGTRT </p>
          <p >ALSVVTWNSKGKTIKTTPEGTEEWSAAPLVTAMCLLGNVSFPCDRPPTCYTREPSRALDI </p>
          <p >LEENVNHEAYDTLLNAILRCGSSGRSKRSVIDDFTLTSPYLGTCSYCHHTVPCFSPVKIE </p>
          <p >QVWDEADDNTIRIQTSAQFGYDQSGAASANKYRYMSLKQDHTVKEGTMDDIKISTSGPCR </p>
          <p >RLSYKGYFLLAKCPPGDSVTVSIVSSNSATSCTLARKIKPKFVGREKYDLPPVHGKKIPC </p>
          <p >TVYDRLKETTAGYITMHRPRPHAYTSYLEESSGKVYAKPPSGKNITYECKCGDYKTGTVS </p>
          <p >TRTEITGCTAIKQCVAYKSDQTKWVFNSPDLIRHDDHTAQGKLHLPFKLIPSTCMVPVAH </p>
          <p >APNVIHGFKHISLQLDTDHLTLLTTRRLGANPEPTTEWIVGKTVRNFTVDRDGLEYIWGN </p>
          <p >HEPVRVYAQESAPGDPHGWPHEIVQHYYHRHPVYTILAVASATVAMMIGVTVAVLCACKA </p>
          <p >RRECLTPYALAPNAVIPTSLALLCCVRSANAETFTETMSYLWSNSQPFFWVQLCIPLAAF </p>
          <p >IVLMRCCSCCLPFLVVAGAYLAKVDAYEHATTVPNVPQIPYKALVERAGYAPLNLEITVM </p>
          <p >SSEVLPSTNQEYITCKFTTVVPSPKIKCCGSLECQPAAHADYTCKVFGGVYPFMWGGAQC </p>
          <p >FCDSENSQMSEAYVELSADCASDHAQAIKVHTAAMKVGLRIVYGNTTSFLDVYVNGVTPG </p>
          <p >TSKDLKVIAGPISASFTPFDHKVVIHRGLVYNYDFPEYGAMKPGAFGDIQATSLTSKDLI </p>
          <p >ASTDIRLLKPSAKNVHVPYTQASSGFEMWKNNSGRPLQETAPFGCKIAVNPLRAVDCSYG </p>
          <p >NIPISIDIPNAAFIRTSDAPLVSTVKCEVSECTYSADFGGMATLQYVSDREGQCPVHSHS </p>
          <p >STATLQESTVHVLEKGAVTVHFSTASPQANFIVSLCGKKTTCNAECKPPADHIVSTPHKN </p>
          <p >DQEFQAAISKTSWSWLFALFGGASSLLIIGLMIFACSMMLTSTRR </p></td>
      </tr>
    </table></td>
  </tr>
</table>
</body>
</html>
