// Assembly Utils, Version 0.0.0.0

[assembly: System.Reflection.AssemblyVersion("0.0.0.0")]
[assembly: System.Reflection.AssemblyAlgorithmId(0)]
[assembly: System.Reflection.AssemblyFileVersion("2.4.10.115")]
[assembly: System.Reflection.AssemblyCopyright("Copyright(C)月亮  http://ycmoon.008.net  QQ:817647 ycmoon.008.net")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("月亮  http://ycmoon.008.net 【http://ycmoon.008.net】")]
[assembly: Xenocode.Client.Attributes.AssemblyAttributes.SuppressDisassembly]
[assembly: Xenocode.Client.Attributes.AssemblyAttributes.ProcessedByXenocode]
[assembly: System.Reflection.AssemblyProduct("Utils.dll")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.InteropServices.Guid("a1fbfd8d-8b61-4f7d-9e9e-b38af5a9f877")]
[assembly: System.Reflection.AssemblyTitle("C#常用工具类合集")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyTrademark("kenny")]
[assembly: System.Reflection.AssemblyDescription("C#常用工具类合集")]
