// Assembly EntLib.Controls.WinForm, Version 1.0.0.0

[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Runtime.CompilerServices.Extension]
[assembly: System.Runtime.InteropServices.Guid("7b77496f-9243-46d7-bcd1-dd3ee8292e94")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyTitle("EntLib.Controls.WinForm")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("微软中国")]
[assembly: System.Reflection.AssemblyProduct("EntLib.Controls.WinForm")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 微软中国 2011")]
[assembly: System.Reflection.AssemblyTrademark("")]
