using System;
using System.Collections.Generic;
using System.Text;

namespace NewLife.WMI
{
    /// <summary>WMI常量类</summary>>
    internal class WMIConst
    {
        public const string WMIROOT = "Root";
        public const string CIMV2 = "CIMV2";

        //DNS常量
        public const string MicrosoftDNS = "MicrosoftDNS";

        //事务日志常量
        public const string Win32_NTLogEvent = "Win32_NTLogEvent";
        public const string Win32_NTEventlogFile = "Win32_NTEventlogFile";

        //PingStatus常量
        public const string Win32_PingStatus = "Win32_PingStatus";

        //Processor常量
        public const string Win32_Processor = "Win32_Processor";

        //ComputerSystem常量
        public const string Win32_ComputerSystem = "Win32_ComputerSystem";

        //OperatingSystem常量
        public const string Win32_OperatingSystem = "Win32_OperatingSystem";

        //Win32_BIOS常量
        public const string Win32_BIOS = "Win32_BIOS";

        //Win32_LogicalDisk常量
        public const string Win32_LogicalDisk = "Win32_LogicalDisk";

        //Win32_NetworkAdapterConfiguration常量
        public const string Win32_NetworkAdapterConfiguration = "Win32_NetworkAdapterConfiguration";
        //Win32_NetworkAdapter常量
        public const string Win32_NetworkAdapter = "Win32_NetworkAdapter";

        //Win32_ComputerSystemProduct常量
        public const string Win32_ComputerSystemProduct = "Win32_ComputerSystemProduct";

        //Win32_Printer常量
        public const string Win32_Printer = "Win32_Printer";

        //Win32_TerminalServiceSetting常量
        public const string Win32_TerminalServiceSetting = "Win32_TerminalServiceSetting";

        //Win32_DisplayConfiguration常量
        public const string Win32_DisplayConfiguration = "Win32_DisplayConfiguration";

        // Win32_CDROMDrive
        public const string Win32_CDROMDrive = "Win32_CDROMDrive";

        //Win32_SoundDevice
        public const string Win32_SoundDevice = "Win32_SoundDevice";

        /// <summary>TCP端口对应服务名称</summary>>
        public static readonly string[,] TcpPortName = {
            {"1","tcpmux(tcp port service multiplexer)"},
            {"2","compressnet(management utility)"},
            {"3","compressnet(compression process)"},
            {"5","rje(remote job entry)"},
            {"7","echo(echo)"},
            {"9","discard(discard)"},
            {"11","systat(active users)"},
            {"13","daytime(daytime)"},
            {"17","qotd(quote of the day)"},
            {"18","msp(message send protocol)"},
            {"19","chargen(character generator)"},
            {"20","ftp-data(file transfer [default data])"},
            {"21","ftp(file transfer [control])"},
            {"22","ssh(ssh remote login protocol)"},
            {"23","telnet(telnet)"},
            {"24","(any private mail system)"},
            {"25","smtp(simple mail transfer)"},
            {"27","nsw-fe(nsw user system fe)"},
            {"29","msg-icp(msg icp)"},
            {"31","msg-auth(msg authentication)"},
            {"33","dsp(display support protocol)"},
            {"35","(any private printer server)"},
            {"37","time(time)"},
            {"38","rap(route access protocol)"},
            {"39","rlp(resource location protocol)"},
            {"41","graphics(graphics)"},
            {"42","nameserver(wins host name server)"},
            {"43","nicname(who is)"},
            {"44","mpm-flags(mpm flags protocol)"},
            {"45","mpm(message processing module [recv])"},
            {"46","mpm-snd(mpm [default send])"},
            {"47","ni-ftp(ni ftp)"},
            {"48","auditd(digital audit daemon)"},
            {"49","tacacs(login host protocol (tacacs))"},
            {"50","re-mail-ck(remote mail checking protocol)"},
            {"51","la-maint(imp logical address maintenance)"},
            {"52","xns-time(xns time protocol)"},
            {"53","domain(domain name server)"},
            {"54","xns-ch(xns clearinghouse)"},
            {"55","isi-gl(isi graphics language)"},
            {"56","xns-auth(xns authentication)"},
            {"57","(any private terminal access)"},
            {"58","xns-mail(xns mail)"},
            {"59","(any private file service)"},
            {"60","(unassigned)"},
            {"61","ni-mail(ni mail)"},
            {"62","acas(aca services)"},
            {"63","whois+whois+()"},
            {"64","covia(communications integrator (ci))"},
            {"65","tacacs-ds(tacacs-database service)"},
            {"66","sql*net(oracle sql*net)"},
            {"67","bootps(bootstrap protocol server)"},
            {"68","bootpc(bootstrap protocol client)"},
            {"69","tftp(trivial file transfer)"},
            {"70","gopher(gopher)"},
            {"71","netrjs-1(remote job service)"},
            {"72","netrjs-2(remote job service)"},
            {"73","netrjs-3(remote job service)"},
            {"74","netrjs-4(remote job service)"},
            {"75","(any private dial out service)"},
            {"76","deos(distributed external object store)"},
            {"77","(any private rje service)"},
            {"78","vettcp(vettcp)"},
            {"79","finger(finger)"},
            {"80","http(world wide web http)"},
            {"81","hosts2-ns(hosts2 name server)"},
            {"82","xfer(xfer utility)"},
            {"83","mit-ml-dev(mit ml device)"},
            {"84","ctf(common trace facility)"},
            {"85","mit-ml-dev(mit ml device)"},
            {"86","mfcobol(micro focus cobol)"},
            {"87","(any private terminal link)"},
            {"88","kerberos(kerberos)"},
            {"89","su-mit-tg(su/mit telnet gateway)"},
            {"90","dnsix(dnsix securit attribute token map)"},
            {"91","mit-dov(mit dover spooler)"},
            {"92","npp(network printing protocol)"},
            {"93","dcp(device control protocol)"},
            {"94","objcall(tivoli object dispatcher)"},
            {"95","supdup(supdup)"},
            {"96","dixie(dixie protocol specification)"},
            {"97","swift-rvf(swift remote virtural file protocol)"},
            {"98","tacnews(tac news)"},
            {"99","metagram(metagram relay)"},
            {"100","newacct([unauthorized use])"},
            {"101","hostname(nic host name server)"},
            {"102","iso-tsap(iso-tsap class 0)"},
            {"103","gppitnp(genesis point-to-point trans net)"},
            {"104","acr-nema(acr-nema digital imag. & comm. 300)"},
            {"105","cso(ccso name server protocol)"},
            {"106","3com-tsmux(3com-tsmux)"},
            {"107","rtelnet(remote telnet service)"},
            {"108","snagas(sna gateway access server)"},
            {"109","pop2(post office protocol - version 2)"},
            {"110","pop3(post office protocol - version 3)"},
            {"111","sunrpc(sun remote procedure call)"},
            {"112","mcidas(mcidas data transmission protocol)"},
            {"113","auth(authentication service)"},
            {"114","audionews(audio news multicast)"},
            {"115","sftp(simple file transfer protocol)"},
            {"116","ansanotify(ansa rex notify)"},
            {"117","uucp-path(uucp path service)"},
            {"118","sqlserv(sql services)"},
            {"119","nntp(network news transfer protocol)"},
            {"120","cfdptkt(cfdptkt)"},
            {"121","erpc(encore expedited remote pro.call)"},
            {"122","smakynet(smakynet)"},
            {"123","ntp(network time protocol)"},
            {"124","ansatrader(ansa rex trader)"},
            {"125","locus-map(locus pc-interface net map ser)"},
            {"126","unitary(unisys unitary login)"},
            {"127","locus-con(locus pc-interface conn server)"},
            {"128","gss-xlicen(gss x license verification)"},
            {"129","pwdgen(password generator protocol)"},
            {"130","cisco-fna(cisco fnative)"},
            {"131","cisco-tna(cisco tnative)"},
            {"132","cisco-sys(cisco sysmaint)"},
            {"133","statsrv(statistics service)"},
            {"134","ingres-net(ingres-net service)"},
            {"135","epmap(dce endpoint resolution)"},
            {"136","profile(profile naming system)"},
            {"137","netbios-ns(netbios name service)"},
            {"138","netbios-dgm(netbios datagram service)"},
            {"139","netbios-ssn(netbios session service)"},
            {"140","emfis-data(emfis data service)"},
            {"141","emfis-cntl(emfis control service)"},
            {"142","bl-idm(britton-lee idm)"},
            {"143","imap(internet message access protocol)"},
            {"144","news(news)"},
            {"145","uaac(uaac protocol)"},
            {"146","iso-tp0(iso-ip0)"},
            {"147","iso-ip(iso-ip)"},
            {"148","jargon(jargon)"},
            {"149","aed-512(aed 512 emulation service)"},
            {"150","sql-net(sql-net)"},
            {"151","hems(hems)"},
            {"152","bftp(background file transfer program)"},
            {"153","sgmp(sgmp)"},
            {"154","netsc-prod(netsc)"},
            {"155","netsc-dev(netsc)"},
            {"156","sqlsrv(sql service)"},
            {"157","knet-cmp(knet/vm command/message protocol)"},
            {"158","pcmail-srv(pcmail server)"},
            {"159","nss-routing(nss-routing)"},
            {"160","sgmp-traps(sgmp-traps)"},
            {"161","snmp(snmp)"},
            {"162","snmptrap(snmptrap)"},
            {"163","cmip-man(cmip manager)"},
            {"164","cmip-agent(cmip agent)"},
            {"165","xns-courier(xerox)"},
            {"166","s-net(sirius systems)"},
            {"167","namp(namp)"},
            {"168","rsvd(rsvd)"},
            {"169","send(send)"},
            {"170","print-srv(network postscript)"},
            {"171","multiplex(network innovations multiplex)"},
            {"172","cl/1(network innovations cl/1)"},
            {"173","xyplex-mux(xyplex)"},
            {"174","mailq(mailq)"},
            {"175","vmnet(vmnet)"},
            {"176","genrad-mux(genrad-mux)"},
            {"177","xdmcp(x display manager control protocol)"},
            {"178","nextstep(nextstep window server)"},
            {"179","bgp(border gateway protocol)"},
            {"180","ris(intergraph)"},
            {"181","unify(unify)"},
            {"182","audit(unisys audit sitp)"},
            {"183","ocbinder(ocbinder)"},
            {"184","ocserver(ocserver)"},
            {"185","remote-kis(remote-kis)"},
            {"186","kis(kis protocol)"},
            {"187","aci(application communication interface)"},
            {"188","mumps(plus fives mumps)"},
            {"189","qft(queued file transport)"},
            {"190","gacp(gateway access control protocol)"},
            {"191","prospero(prospero directory service)"},
            {"192","osu-nms(osu network monitoring system)"},
            {"193","srmp(spider remote monitoring protocol)"},
            {"194","irc(internet relay chat protocol)"},
            {"195","dn6-nlm-aud(dnsix network level module audit)"},
            {"196","dn6-smm-red(dnsix session mgt module audit redir)"},
            {"197","dls(directory location service)"},
            {"198","dls-mon(directory location service monitor)"},
            {"199","smux(smux)"},
            {"200","src(ibm system resource controller)"},
            {"201","at-rtmp(appletalk routing maintenance)"},
            {"202","at-nbp(appletalk name binding)"},
            {"203","at-3(appletalk unused)"},
            {"204","at-echo(appletalk echo)"},
            {"205","at-5(appletalk unused)"},
            {"206","at-zis(appletalk zone information)"},
            {"207","at-7(appletalk unused)"},
            {"208","at-8(appletalk unused)"},
            {"209","qmtp(the quick mail transfer protocol)"},
            {"210","z39.50(ansi z39.50)"},
            {"211","914c/g(texas instruments 914c/g terminal)"},
            {"212","anet(atexsstr)"},
            {"213","ipx(ipx)"},
            {"214","vmpwscs(vm pwscs)"},
            {"215","softpc(insignia solutions)"},
            {"216","cailic(computer associates intl license server)"},
            {"217","dbase(dbase unix)"},
            {"218","mpp(netix message posting protocol)"},
            {"219","uarps(unisys arps)"},
            {"220","imap3(interactive mail access protocol v3)"},
            {"221","fln-spx(berkeley rlogind with spx auth)"},
            {"222","rsh-spx(berkeley rshd with spx auth)"},
            {"223","cdc(certificate distribution center)"},
            {"242","direct(direct)"},
            {"243","sur-meas(survey measurement)"},
            {"244","dayna(dayna)"},
            {"245","link(link)"},
            {"246","dsp3270(display systems protocol)"},
            {"256","rap(rap)"},
            {"257","set(secure electronic transaction)"},
            {"258","yak-chat(yak winsock personal chat)"},
            {"259","esro-gen(efficient short remote operations)"},
            {"260","openport(openport)"},
            {"261","naming-iiop-ssl(iiop naming service (ssl))"},
            {"262","arcisdms(arcisdms)"},
            {"263","hdap(hdap)"},
            {"280","http-mgmt(http-mgmt)"},
            {"281","personal-link(personal link)"},
            {"282","cableport-ax(cable port a/x)"},
            {"309","entrusttime(entrusttime)"},
            {"344","pdap(prospero data access protocol)"},
            {"345","pawserv(perf analysis workbench)"},
            {"346","zserv(zebra server)"},
            {"347","fatserv(fatmen server)"},
            {"348","csi-sgwp(cabletron management protocol)"},
            {"349","mftp(mftp)"},
            {"350","matip-type-a(matip type a)"},
            {"351","matip-type-b(matip type b)"},
            {"371","clearcase(clearcase)"},
            {"372","ulistproc(listprocessor)"},
            {"373","legent-1(legent corporation)"},
            {"374","legent-2(legent corporation)"},
            {"375","hassle(hassle)"},
            {"376","nip(amiga envoy network inquiry proto)"},
            {"377","tnetos(nec corporation)"},
            {"378","dsetos(nec corporation)"},
            {"379","is99c(tia/eia/is-99 modem client)"},
            {"380","is99s(tia/eia/is-99 modem server)"},
            {"381","hp-collector(hp performance data collector)"},
            {"382","hp-managed-node(hp performance data managed node)"},
            {"383","hp-alarm-mgr(hp performance data alarm manager)"},
            {"384","arns(a remote network server system)"},
            {"385","ibm-app(ibm application)"},
            {"386","asa(asa message router object def.)"},
            {"387","aurp(appletalk update-based routing pro.)"},
            {"388","unidata-ldm(unidata ldm version 4)"},
            {"389","ldap(lightweight directory access protocol)"},
            {"390","uis(uis)"},
            {"391","synotics-relay(synoptics snmp relay port)"},
            {"392","synotics-broker(synoptics port broker port)"},
            {"393","dis(data interpretation system)"},
            {"394","embl-ndt(embl nucleic data transfer)"},
            {"395","netcp(netscout control protocol)"},
            {"396","netware-ip(novell netware over ip)"},
            {"397","mptn(multi protocol trans. net.)"},
            {"398","kryptolan(kryptolan)"},
            {"399","iso-tsap-c2(iso transport class 2 non-control over tcp)"},
            {"400","work-sol(workstation solutions)"},
            {"401","ups(uninterruptible power supply)"},
            {"402","genie(genie protocol)"},
            {"403","decap(decap)"},
            {"404","nced(nced)"},
            {"405","ncld(ncld)"},
            {"406","imsp(interactive mail support protocol)"},
            {"407","timbuktu(timbuktu)"},
            {"408","prm-sm(prospero resource manager sys. man.)"},
            {"409","prm-nm(prospero resource manager node man.)"},
            {"410","decladebug(decladebug remote debug protocol)"},
            {"411","rmt(remote mt protocol)"},
            {"412","synoptics-trap(trap convention port)"},
            {"413","smsp(smsp)"},
            {"414","infoseek(infoseek)"},
            {"415","bnet(bnet)"},
            {"416","silverplatter(silverplatter)"},
            {"417","onmux(onmux)"},
            {"418","hyper-g(hyper-g)"},
            {"419","ariel1(ariel)"},
            {"420","smpte(smpte)"},
            {"421","ariel2(ariel)"},
            {"422","ariel3(ariel)"},
            {"423","opc-job-start(ibm operations planning and control start)"},
            {"424","opc-job-track(ibm operations planning and control track)"},
            {"425","icad-el(icad)"},
            {"426","smartsdp(smartsdp)"},
            {"427","svrloc(server location)"},
            {"428","ocs_cmu(ocs_cmu)"},
            {"429","ocs_amu(ocs_amu)"},
            {"430","utmpsd(utmpsd)"},
            {"431","utmpcd(utmpcd)"},
            {"432","iasd(iasd)"},
            {"433","nnsp(nnsp)"},
            {"434","mobileip-agent(mobileip-agent)"},
            {"435","mobilip-mn(mobilip-mn)"},
            {"436","dna-cml(dna-cml)"},
            {"437","comscm(comscm)"},
            {"438","dsfgw(dsfgw)"},
            {"439","dasp(dasp thomas obermair)"},
            {"440","sgcp(sgcp)"},
            {"441","decvms-sysmgt(decvms-sysmgt)"},
            {"442","cvc_hostd(cvc_hostd)"},
            {"443","https(https mcom)"},
            {"444","snpp(simple network paging protocol)"},
            {"445","microsoft-ds(microsoft-ds)"},
            {"446","ddm-rdb(ddm-rdb)"},
            {"447","ddm-dfm(ddm-rfm)"},
            {"448","ddm-byte(ddm-byte)"},
            {"449","as-servermap(as server mapper)"},
            {"450","tserver(tserver)"},
            {"451","sfs-smp-net(cray network semaphore server)"},
            {"452","sfs-config(cray sfs config server)"},
            {"453","creativeserver(creativeserver)"},
            {"454","contentserver(contentserver)"},
            {"455","creativepartnr(creativepartnr)"},
            {"456","macon-tcp(macon-tcp)"},
            {"457","scohelp(scohelp)"},
            {"458","appleqtc(apple quick time)"},
            {"459","ampr-rcmd(ampr-rcmd)"},
            {"460","skronk(skronk)"},
            {"461","datasurfsrv(datarampsrv)"},
            {"462","datasurfsrvsec(datarampsrvsec)"},
            {"463","alpes(alpes)"},
            {"464","kpasswd(kpasswd)"},
            {"465","ssmtp(ssmtp)"},
            {"466","digital-vrc(digital-vrc)"},
            {"467","mylex-mapd(mylex-mapd)"},
            {"468","photuris(proturis)"},
            {"469","rcp(radio control protocol)"},
            {"470","scx-proxy(scx-proxy)"},
            {"471","mondex(mondex)"},
            {"472","ljk-login(ljk-login)"},
            {"473","hybrid-pop(hybrid-pop)"},
            {"474","tn-tl-w1(tn-tl-w1)"},
            {"475","tcpnethaspsrv(tcpnethaspsrv)"},
            {"476","tn-tl-fd1(tn-tl-fd1)"},
            {"477","ss7ns(ss7ns)"},
            {"478","spsc(spsc)"},
            {"479","iafserver(iafserver)"},
            {"480","iafdbase(iafdbase)"},
            {"481","ph(ph service)"},
            {"482","bgs-nsi(bgs-nsi)"},
            {"483","ulpnet(ulpnet)"},
            {"484","integra-sme(integra software management environment)"},
            {"485","powerburst(air soft power burst)"},
            {"486","avian(avian)"},
            {"487","saft(saft)"},
            {"488","gss-http(gss-http)"},
            {"489","nest-protocol(nest-protocol)"},
            {"490","micom-pfs(micom-pfs)"},
            {"491","go-login(go-login)"},
            {"492","ticf-1(transport independent convergence for fna)"},
            {"493","ticf-2(transport independent convergence for fna)"},
            {"494","pov-ray(pov-ray)"},
            {"495","intecourier(intecourier)"},
            {"496","pim-rp-disc(pim-rp-disc)"},
            {"497","dantz(dantz)"},
            {"498","siam(siam)"},
            {"499","iso-ill(iso ill protocol)"},
            {"500","isakmp(isakmp)"},
            {"501","stmf(stmf)"},
            {"502","asa-appl-proto(asa-appl-proto)"},
            {"503","intrinsa(intrinsa)"},
            {"504","citadel(citadel)"},
            {"505","mailbox-lm(mailbox-lm)"},
            {"506","ohimsrv(ohimsrv)"},
            {"507","crs(crs)"},
            {"508","xvttp(xvttp)"},
            {"509","snare(snare)"},
            {"510","fcp(firstclass protocol)"},
            {"511","mynet(mynet-as)"},
            {"512","exec(remote process execution;)"},
            {"513","login(remote login a la telnet;)"},
            {"514","shell(cmd)"},
            {"515","printer(spooler)"},
            {"516","videotex(videotex)"},
            {"517","talk(like tenex link)"},
            {"518","ntalk"},
            {"519","utime(unixtime)"},
            {"520","efs(extended file name server)"},
            {"521","ripng(ripng)"},
            {"522","ulp(ulp)"},
            {"523","ibm-db2(ibm-db2)"},
            {"524","ncp(ncp)"},
            {"525","timed(timeserver)"},
            {"526","tempo(newdate)"},
            {"527","stx(stock ixchange)"},
            {"528","custix(customer ixchange)"},
            {"529","irc-serv(irc-serv)"},
            {"530","courier(rpc)"},
            {"531","conference(chat)"},
            {"532","netnews(readnews)"},
            {"533","netwall(for emergency broadcasts)"},
            {"534","mm-admin(megamedia admin)"},
            {"535","iiop(iiop)"},
            {"536","opalis-rdv(opalis-rdv)"},
            {"537","nmsp(networked media streaming protocol)"},
            {"538","gdomap(gdomap)"},
            {"539","apertus-ldp(apertus technologies load determination)"},
            {"540","uucp(uucpd)"},
            {"541","uucp-rlogin(uucp-rlogin)"},
            {"542","commerce(commerce)"},
            {"543","klogin"},
            {"544","kshell(krcmd)"},
            {"545","appleqtcsrvr(appleqtcsrvr)"},
            {"546","dhcpv6-client(dhcpv6 client)"},
            {"547","dhcpv6-server(dhcpv6 server)"},
            {"548","afpovertcp(afp over tcp)"},
            {"549","idfp(idfp)"},
            {"550","new-rwho(new-who)"},
            {"551","cybercash(cybercash)"},
            {"552","deviceshare(deviceshare)"},
            {"553","pirp(pirp)"},
            {"554","rtsp(real time stream control protocol)"},
            {"555","dsf"},
            {"556","remotefs(rfs server)"},
            {"557","openvms-sysipc(openvms-sysipc)"},
            {"558","sdnskmp(sdnskmp)"},
            {"559","teedtap(teedtap)"},
            {"560","rmonitor(rmonitord)"},
            {"561","monitor"},
            {"562","chshell(chcmd)"},
            {"563","snews(snews)"},
            {"564","9pfs(plan 9 file service)"},
            {"565","whoami(whoami)"},
            {"566","streettalk(streettalk)"},
            {"567","banyan-rpc(banyan-rpc)"},
            {"568","ms-shuttle(microsoft shuttle)"},
            {"569","ms-rome(microsoft rome)"},
            {"570","meter(demon)"},
            {"571","meter(udemon)"},
            {"572","sonar(sonar)"},
            {"573","banyan-vip(banyan-vip)"},
            {"574","ftp-agent(ftp software agent system)"},
            {"575","vemmi(vemmi)"},
            {"576","ipcd(ipcd)"},
            {"577","vnas(vnas)"},
            {"578","ipdd(ipdd)"},
            {"579","decbsrv(decbsrv)"},
            {"580","sntp-heartbeat(sntp heartbeat)"},
            {"581","bdp(bundle discovery protocol)"},
            {"600","ipcserver(sun ipc server)"},
            {"606","urm(cray unified resource manager)"},
            {"607","nqs(nqs)"},
            {"608","nsift-uft(sender-initiated/unsolicited file transfer)"},
            {"609","npmp-trap(npmp-trap)"},
            {"610","npmp-local(npmp-local)"},
            {"611","npmp-gui(npmp-gui)"},
            {"612","hmmp-ind(hmmp indication)"},
            {"613","hmmp-op(hmmp operation)"},
            {"614","sshell(sslshell)"},
            {"615","sco-inetmgr(internet configuration manager)"},
            {"616","sco-sysmgr(sco system administration server)"},
            {"617","sco-dtmgr(sco desktop administration server)"},
            {"618","dei-icda(dei-icda)"},
            {"619","digital-evm(digital evm)"},
            {"620","sco-websrvrmgr(sco webserver manager)"},
            {"633","servstat(service status update (sterling software))"},
            {"634","ginad(ginad)"},
            {"635","rlzdbase(rlz dbase)"},
            {"636","ssl-ldap(ssl-ldap)"},
            {"637","lanserver(lanserver)"},
            {"666","mdqs"},
            {"667","disclose(campaign contribution disclosures - sdr technologies)"},
            {"668","mecomm(mecomm)"},
            {"669","meregister(meregister)"},
            {"670","vacdsm-sws(vacdsm-sws)"},
            {"671","vacdsm-app(vacdsm-app)"},
            {"672","vpps-qua(vpps-qua)"},
            {"673","cimplex(cimplex)"},
            {"674","acap(acap)"},
            {"704","elcsd(errlog copy/server daemon)"},
            {"705","agentx(agentx)"},
            {"709","entrust-kmsh(entrust key management service handler)"},
            {"710","entrust-ash(entrust administration service handler)"},
            {"729","netviewdm1(ibm netview dm/6000 server/client)"},
            {"730","netviewdm2(ibm netview dm/6000 send)"},
            {"731","netviewdm3(ibm netview dm/6000 receive)"},
            {"741","netgw(netgw)"},
            {"742","netrcs(network based rev. cont. sys.)"},
            {"744","flexlm(flexible license manager)"},
            {"747","fujitsu-dev(fujitsu device control)"},
            {"748","ris-cm(russell info sci calendar manager)"},
            {"749","kerberos-adm(kerberos administration)"},
            {"750","rfile"},
            {"751","pump"},
            {"752","qrh"},
            {"753","rrh"},
            {"754","tell(send)"},
            {"758","nlogin"},
            {"759","con"},
            {"760","ns"},
            {"761","rxe"},
            {"762","quotad"},
            {"763","cycleserv"},
            {"764","omserv"},
            {"765","webster"},
            {"767","phonebook(phone)"},
            {"769","vid"},
            {"770","cadlock"},
            {"771","rtip"},
            {"772","cycleserv2"},
            {"773","submit"},
            {"774","rpasswd"},
            {"775","entomb"},
            {"776","wpages"},
            {"780","wpgs"},
            {"786","concert(concert)"},
            {"800","mdbs_daemon"},
            {"801","device"},
            {"886","iclcnet-locate(icl conetion locate server)"},
            {"887","iclcnet_svinfo(icl conetion server info)"},
            {"888","accessbuilder(accessbuilder)"},
            {"911","xact-backup(xact-backup)"},
            {"991","nas(netnews administration system)"},
            {"995","spop3(ssl based pop3)"},
            {"996","vsinet(vsinet)"},
            {"997","maitrd"},
            {"998","busboy"},
            {"999","garcon"},
            {"1000","cadlock"},
            {"1023","(reserved)"},
            {"1024","(reserved)"},
            {"1025","blackjack(network blackjack)"},
            {"1027","icq(icq?)"},
            {"1030","iad1(bbn iad)"},
            {"1031","iad2(bbn iad)"},
            {"1032","iad3(bbn iad)"},
            {"1047","neod1(suns neo object request broker)"},
            {"1048","neod2(suns neo object request broker)"},
            {"1058","nim(nim)"},
            {"1059","nimreg(nimreg)"},
            {"1067","instl_boots(installation bootstrap proto. serv.)"},
            {"1068","instl_bootc(installation bootstrap proto. cli.)"},
            {"1080","socks(socks)"},
            {"1083","ansoft-lm-1(anasoft license manager)"},
            {"1084","ansoft-lm-2(anasoft license manager)"},
            {"1110","nfsd-status(cluster status info)"},
            {"1123","murray(murray)"},
            {"1155","nfa(network file access)"},
            {"1212","lupa(lupa)"},
            {"1222","nerv(sni r&d network)"},
            {"1248","hermes"},
            {"1313","bmc_patroldb(bmc_patroldb)"},
            {"1314","pdps(photoscript distributed printing system)"},
            {"1345","vpjp(vpjp)"},
            {"1346","alta-ana-lm(alta analytics license manager)"},
            {"1347","bbn-mmc(multi media conferencing)"},
            {"1348","bbn-mmx(multi media conferencing)"},
            {"1349","sbook(registration network protocol)"},
            {"1350","editbench(registration network protocol)"},
            {"1351","equationbuilder(digital tool works (mit))"},
            {"1352","lotusnote(lotus note)"},
            {"1353","relief(relief consulting)"},
            {"1354","rightbrain(rightbrain software)"},
            {"1355","intuitive edge(intuitive edge)"},
            {"1356","cuillamartin(cuillamartin company)"},
            {"1357","pegboard(electronic pegboard)"},
            {"1358","connlcli(connlcli)"},
            {"1359","ftsrv(ftsrv)"},
            {"1360","mimer(mimer)"},
            {"1361","linx(linx)"},
            {"1362","timeflies(timeflies)"},
            {"1363","ndm-requester(network datamover requester)"},
            {"1364","ndm-server(network datamover server)"},
            {"1365","adapt-sna(network software associates)"},
            {"1366","netware-csp(novell netware comm service platform)"},
            {"1367","dcs(dcs)"},
            {"1368","screencast(screencast)"},
            {"1369","gv-us(globalview to unix shell)"},
            {"1370","us-gv(unix shell to globalview)"},
            {"1371","fc-cli(fujitsu config protocol)"},
            {"1372","fc-ser(fujitsu config protocol)"},
            {"1373","chromagrafx(chromagrafx)"},
            {"1374","molly(epi software systems)"},
            {"1375","bytex(bytex)"},
            {"1376","ibm-pps(ibm person to person software)"},
            {"1377","cichlid(cichlid license manager)"},
            {"1378","elan(elan license manager)"},
            {"1379","dbreporter(integrity solutions)"},
            {"1380","telesis-licman(telesis network license manager)"},
            {"1381","apple-licman(apple network license manager)"},
            {"1382","udt_os"},
            {"1383","gwha(gw hannaway network license manager)"},
            {"1384","os-licman(objective solutions license manager)"},
            {"1385","atex_elmd(atex publishing license manager)"},
            {"1386","checksum(checksum license manager)"},
            {"1387","cadsi-lm(computer aided design software inc lm)"},
            {"1388","objective-dbc(objective solutions database cache)"},
            {"1389","iclpv-dm(document manager)"},
            {"1390","iclpv-sc(storage controller)"},
            {"1391","iclpv-sas(storage access server)"},
            {"1392","iclpv-pm(print manager)"},
            {"1393","iclpv-nls(network log server)"},
            {"1394","iclpv-nlc(network log client)"},
            {"1395","iclpv-wsm(pc workstation manager software)"},
            {"1396","dvl-activemail(dvl active mail)"},
            {"1397","audio-activmail(audio active mail)"},
            {"1398","video-activmail(video active mail)"},
            {"1399","cadkey-licman(cadkey license manager)"},
            {"1400","cadkey-tablet(cadkey tablet daemon)"},
            {"1401","goldleaf-licman(goldleaf license manager)"},
            {"1402","prm-sm-np(prospero resource manager)"},
            {"1403","prm-nm-np(prospero resource manager)"},
            {"1404","igi-lm(infinite graphics license manager)"},
            {"1405","ibm-res(ibm remote execution starter)"},
            {"1406","netlabs-lm(netlabs license manager)"},
            {"1407","dbsa-lm(dbsa license manager)"},
            {"1408","sophia-lm(sophia license manager)"},
            {"1409","here-lm(here license manager)"},
            {"1410","hiq(hiq license manager)"},
            {"1411","af(audiofile)"},
            {"1412","innosys(innosys)"},
            {"1413","innosys-acl(innosys-acl)"},
            {"1414","ibm-mqseries(ibm mqseries)"},
            {"1415","dbstar(dbstar)"},
            {"1416","novell-lu6.2(novell lu6.2)"},
            {"1417","timbuktu-srv1(timbuktu service 1 port)"},
            {"1418","timbuktu-srv2(timbuktu service 2 port)"},
            {"1419","timbuktu-srv3(timbuktu service 3 port)"},
            {"1420","timbuktu-srv4(timbuktu service 4 port)"},
            {"1421","gandalf-lm(gandalf license manager)"},
            {"1422","autodesk-lm(autodesk license manager)"},
            {"1423","essbase(essbase arbor software)"},
            {"1424","hybrid(hybrid encryption protocol)"},
            {"1425","zion-lm(zion software license manager)"},
            {"1426","sais(satellite-data acquisition system 1)"},
            {"1427","mloadd(mloadd monitoring tool)"},
            {"1428","informatik-lm(informatik license manager)"},
            {"1429","nms(hypercom nms)"},
            {"1430","tpdu(hypercom tpdu)"},
            {"1431","rgtp(reverse gossip transport)"},
            {"1432","blueberry-lm(blueberry software license manager)"},
            {"1433","ms-sql-s(microsoft-sql-server)"},
            {"1434","ms-sql-m(microsoft-sql-monitor)"},
            {"1435","ibm-cics(ibm cics)"},
            {"1436","saism(satellite-data acquisition system 2)"},
            {"1437","tabula(tabula)"},
            {"1438","eicon-server(eicon security agent/server)"},
            {"1439","eicon-x25(eicon x25/sna gateway)"},
            {"1440","eicon-slp(eicon service location protocol)"},
            {"1441","cadis-1(cadis license management)"},
            {"1442","cadis-2(cadis license management)"},
            {"1443","ies-lm(integrated engineering software)"},
            {"1444","marcam-lm(marcam license management)"},
            {"1445","proxima-lm(proxima license manager)"},
            {"1446","ora-lm(optical research associates license manager)"},
            {"1447","apri-lm(applied parallel research lm)"},
            {"1448","oc-lm(openconnect license manager)"},
            {"1449","peport(peport)"},
            {"1450","dwf(tandem distributed workbench facility)"},
            {"1451","infoman(ibm information management)"},
            {"1452","gtegsc-lm(gte government systems license man)"},
            {"1453","genie-lm(genie license manager)"},
            {"1454","interhdl_elmd(interhdl license manager)"},
            {"1455","esl-lm(esl license manager)"},
            {"1456","dca(dca)"},
            {"1457","valisys-lm(valisys license manager)"},
            {"1458","nrcabq-lm(nichols research corp.)"},
            {"1459","proshare1(proshare notebook application)"},
            {"1460","proshare2(proshare notebook application)"},
            {"1461","ibm_wrless_lan(ibm wireless lan)"},
            {"1462","world-lm(world license manager)"},
            {"1463","nucleus(nucleus)"},
            {"1464","msl_lmd(msl license manager)"},
            {"1465","pipes(pipes platform)"},
            {"1466","oceansoft-lm(ocean software license manager)"},
            {"1467","csdmbase(csdmbase)"},
            {"1468","csdm(csdm)"},
            {"1469","aal-lm(active analysis limited license manager)"},
            {"1470","uaiact(universal analytics)"},
            {"1471","csdmbase(csdmbase)"},
            {"1472","csdm(csdm)"},
            {"1473","openmath(openmath)"},
            {"","()"},
            {"1474","telefinder(telefinder)"},
            {"1475","taligent-lm(taligent license manager)"},
            {"1476","clvm-cfg(clvm-cfg)"},
            {"1477","ms-sna-server(ms-sna-server)"},
            {"1478","ms-sna-base(ms-sna-base)"},
            {"1479","dberegister(dberegister)"},
            {"1480","pacerforum(pacerforum)"},
            {"1481","airs(airs)"},
            {"1482","miteksys-lm(miteksys license manager)"},
            {"1483","afs(afs license manager)"},
            {"1484","confluent(confluent license manager)"},
            {"1485","lansource(lansource)"},
            {"1486","nms_topo_serv(nms_topo_serv)"},
            {"1487","localinfosrvr(localinfosrvr)"},
            {"1488","docstor(docstor)"},
            {"1489","dmdocbroker(dmdocbroker)"},
            {"1490","insitu-conf(insitu-conf)"},
            {"1491","anynetgateway(anynetgateway)"},
            {"1492","stone-design-1(stone-design-1)"},
            {"1493","netmap_lm(netmap_lm)"},
            {"1494","ica(ica)"},
            {"1495","cvc(cvc)"},
            {"1496","liberty-lm(liberty-lm)"},
            {"1497","rfx-lm(rfx-lm)"},
            {"1498","watcom-sql(watcom-sql)"},
            {"1499","fhc(federico heinz consultora)"},
            {"1500","vlsi-lm(vlsi license manager)"},
            {"1501","saiscm(satellite-data acquisition system 3)"},
            {"1502","shivadiscovery(shiva)"},
            {"1503","imtc-mcs(databeam)"},
            {"1504","evb-elm(evb software engineering license manager)"},
            {"1505","funkproxy(funk software)"},
            {"1506","utcd(universal time daemon (utcd))"},
            {"1507","symplex(symplex)"},
            {"1508","diagmond(diagmond)"},
            {"1509","robcad-lm(robcad)"},
            {"1510","mvx-lm(midland valley exploration ltd. lic. man.)"},
            {"1511","3l-l1(3l-l1)"},
            {"1512","wins(microsofts windows internet name service)"},
            {"1513","fujitsu-dtc(fujitsu systems business of america)"},
            {"1514","fujitsu-dtcns(fujitsu systems business of america)"},
            {"1515","ifor-protocol(ifor-protocol)"},
            {"1516","vpad(virtual places audio data)"},
            {"1517","vpac(virtual places audio control)"},
            {"1518","vpvd(virtual places video data)"},
            {"1519","vpvc(virtual places video control)"},
            {"1520","atm-zip-office(atm zip office)"},
            {"1521","ncube-lm(ncube license manager)"},
            {"1522","ricardo-lm(ricardo north america license manager)"},
            {"1523","cichild-lm(cichild)"},
            {"1524","ingreslock(ingres)"},
            {"1525","orasrv(oracle)"},
            {"1526","pdap-np(prospero data access prot non-priv)"},
            {"1527","tlisrv(oracle)"},
            {"1528","mciautoreg(micautoreg)"},
            {"1529","coauthor(oracle)"},
            {"1530","rap-service(rap-service)"},
            {"1531","rap-listen(rap-listen)"},
            {"1532","miroconnect(miroconnect)"},
            {"1533","virtual-places(virtual places software)"},
            {"1534","micromuse-lm(micromuse-lm)"},
            {"1535","ampr-info(ampr-info)"},
            {"1536","ampr-inter(ampr-inter)"},
            {"1537","sdsc-lm(isi-lm)"},
            {"1538","3ds-lm(3ds-lm)"},
            {"1539","intellistor-lm(intellistor license manager)"},
            {"1540","rds(rds)"},
            {"1541","rds2(rds2)"},
            {"1542","gridgen-elmd(gridgen-elmd)"},
            {"1543","simba-cs(simba-cs)"},
            {"1544","aspeclmd(aspeclmd)"},
            {"1545","vistium-share(vistium-share)"},
            {"1546","abbaccuray(abbaccuray)"},
            {"1547","laplink(laplink)"},
            {"1548","axon-lm(axon license manager)"},
            {"1549","shivahose(shiva hose)"},
            {"1550","3m-image-lm(image storage license manager 3m company)"},
            {"1551","hecmtl-db(hecmtl-db)"},
            {"1552","pciarray(pciarray)"},
            {"1553","sna-cs(sna-cs)"},
            {"1554","caci-lm(caci products company license manager)"},
            {"1555","livelan(livelan)"},
            {"1556","ashwin(ashwin ci tecnologies)"},
            {"1557","arbortext-lm(arbortext license manager)"},
            {"1558","xingmpeg(xingmpeg)"},
            {"1559","web2host(web2host)"},
            {"1560","asci-val(asci-val)"},
            {"1561","facilityview(facilityview)"},
            {"1562","pconnectmgr(pconnectmgr)"},
            {"1563","cadabra-lm(cadabra license manager)"},
            {"1564","pay-per-view(pay-per-view)"},
            {"1565","winddlb(windd)"},
            {"1566","corelvideo(corelvideo)"},
            {"1567","jlicelmd(jlicelmd)"},
            {"1568","tsspmap(tsspmap)"},
            {"1569","ets(ets)"},
            {"1570","orbixd(orbixd)"},
            {"1571","rdb-dbs-disp(oracle remote data base)"},
            {"1572","chip-lm(chipcom license manager)"},
            {"1573","itscomm-ns(itscomm-ns)"},
            {"1574","mvel-lm(mvel-lm)"},
            {"1575","oraclenames(oraclenames)"},
            {"1576","moldflow-lm(moldflow-lm)"},
            {"1577","hypercube-lm(hypercube-lm)"},
            {"1578","jacobus-lm(jacobus license manager)"},
            {"1579","ioc-sea-lm(ioc-sea-lm)"},
            {"1580","tn-tl-r1(tn-tl-r1)"},
            {"1581","vmf-msg-port(vmf-msg-port)"},
            {"1582","msims(msims)"},
            {"1583","simbaexpress(simbaexpress)"},
            {"1584","tn-tl-fd2(tn-tl-fd2)"},
            {"1585","intv(intv)"},
            {"1586","ibm-abtact(ibm-abtact)"},
            {"1587","pra_elmd(pra_elmd)"},
            {"1588","triquest-lm(triquest-lm)"},
            {"1589","vqp(vqp)"},
            {"1590","gemini-lm(gemini-lm)"},
            {"1591","ncpm-pm(ncpm-pm)"},
            {"1592","commonspace(commonspace)"},
            {"1593","mainsoft-lm(mainsoft-lm)"},
            {"1594","sixtrak(sixtrak)"},
            {"1595","radio(radio)"},
            {"1596","radio-sm(radio-sm)"},
            {"1597","orbplus-iiop(orbplus-iiop)"},
            {"1598","picknfs(picknfs)"},
            {"1599","simbaservices(simbaservices)"},
            {"1600","issd"},
            {"1601","aas(aas)"},
            {"1602","inspect(inspect)"},
            {"1603","picodbc(pickodbc)"},
            {"1604","icabrowser(icabrowser)"},
            {"1605","slp(salutation manager (salutation protocol))"},
            {"1606","slm-api(salutation manager (slm-api))"},
            {"1607","stt(stt)"},
            {"1608","smart-lm(smart corp. license manager)"},
            {"1609","isysg-lm(isysg-lm)"},
            {"1610","taurus-wh(taurus-wh)"},
            {"1611","ill(inter library loan)"},
            {"1612","netbill-trans(netbill transaction server)"},
            {"1613","netbill-keyrep(netbill key repository)"},
            {"1614","netbill-cred(netbill credential server)"},
            {"1615","netbill-auth(netbill authorization server)"},
            {"1616","netbill-prod(netbill product server)"},
            {"1617","nimrod-agent(nimrod inter-agent communication)"},
            {"1618","skytelnet(skytelnet)"},
            {"1619","xs-openstorage(xs-openstorage)"},
            {"1620","faxportwinport(faxportwinport)"},
            {"1621","softdataphone(softdataphone)"},
            {"1622","ontime(ontime)"},
            {"1623","jaleosnd(jaleosnd)"},
            {"1624","udp-sr-port(udp-sr-port)"},
            {"1625","svs-omagent(svs-omagent)"},
            {"1636","cncp(cablenet control protocol)"},
            {"1637","cnap(cablenet admin protocol)"},
            {"1638","cnip(cablenet info protocol)"},
            {"1639","cert-initiator(cert-initiator)"},
            {"1640","cert-responder(cert-responder)"},
            {"1641","invision(invision)"},
            {"1642","isis-am(isis-am)"},
            {"1643","isis-ambc(isis-ambc)"},
            {"1644","saiseh(satellite-data acquisition system 4)"},
            {"1645","datametrics(datametrics)"},
            {"1646","sa-msg-port(sa-msg-port)"},
            {"1647","rsap(rsap)"},
            {"1648","concurrent-lm(concurrent-lm)"},
            {"1649","inspect(inspect)"},
            {"1650","nkd"},
            {"1651","shiva_confsrvr(shiva_confsrvr)"},
            {"1652","xnmp(xnmp)"},
            {"1653","alphatech-lm(alphatech-lm)"},
            {"1654","stargatealerts(stargatealerts)"},
            {"1655","dec-mbadmin(dec-mbadmin)"},
            {"1656","dec-mbadmin-h(dec-mbadmin-h)"},
            {"1657","fujitsu-mmpdc(fujitsu-mmpdc)"},
            {"1658","sixnetudr(sixnetudr)"},
            {"1659","sg-lm(silicon grail license manager)"},
            {"1660","skip-mc-gikreq(skip-mc-gikreq)"},
            {"1661","netview-aix-1(netview-aix-1)"},
            {"1662","netview-aix-2(netview-aix-2)"},
            {"1663","netview-aix-3(netview-aix-3)"},
            {"1664","netview-aix-4(netview-aix-4)"},
            {"1665","netview-aix-5(netview-aix-5)"},
            {"1666","netview-aix-6(netview-aix-6)"},
            {"1667","netview-aix-7(netview-aix-7)"},
            {"1668","netview-aix-8(netview-aix-8)"},
            {"1669","netview-aix-9(netview-aix-9)"},
            {"1670","netview-aix-10(netview-aix-10)"},
            {"1671","netview-aix-11(netview-aix-11)"},
            {"1672","netview-aix-12(netview-aix-12)"},
            {"1673","proshare-mc-1(intel proshare multicast)"},
            {"1674","proshare-mc-2(intel proshare multicast)"},
            {"1675","pdp(pacific data products)"},
            {"1676","netcomm1(netcomm1)"},
            {"1677","groupwise(groupwise)"},
            {"1678","prolink(prolink)"},
            {"1679","darcorp-lm(darcorp-lm)"},
            {"1680","microcom-sbp(microcom-sbp)"},
            {"1681","sd-elmd(sd-elmd)"},
            {"1682","lanyon-lantern(lanyon-lantern)"},
            {"1683","ncpm-hip(ncpm-hip)"},
            {"1684","snaresecure(snaresecure)"},
            {"1685","n2nremote(n2nremote)"},
            {"1686","cvmon(cvmon)"},
            {"1687","nsjtp-ctrl(nsjtp-ctrl)"},
            {"1688","nsjtp-data(nsjtp-data)"},
            {"1689","firefox(firefox)"},
            {"1690","ng-umds(ng-umds)"},
            {"1691","empire-empuma(empire-empuma)"},
            {"1692","sstsys-lm(sstsys-lm)"},
            {"1693","rrirtr(rrirtr)"},
            {"1694","rrimwm(rrimwm)"},
            {"1695","rrilwm(rrilwm)"},
            {"1696","rrifmm(rrifmm)"},
            {"1697","rrisat(rrisat)"},
            {"1698","rsvp-encap-1(rsvp-encapsulation-1)"},
            {"1699","rsvp-encap-2(rsvp-encapsulation-2)"},
            {"1700","mps-raft(mps-raft)"},
            {"1701","l2f(l2f)"},
            {"1702","deskshare(deskshare)"},
            {"1703","hb-engine(hb-engine)"},
            {"1704","bcs-broker(bcs-broker)"},
            {"1705","slingshot(slingshot)"},
            {"1706","jetform(jetform)"},
            {"1707","vdmplay(vdmplay)"},
            {"1708","gat-lmd(gat-lmd)"},
            {"1709","centra(centra)"},
            {"1710","impera(impera)"},
            {"1711","pptconference(pptconference)"},
            {"1712","registrar(resource monitoring service)"},
            {"1713","conferencetalk(conferencetalk)"},
            {"1714","sesi-lm(sesi-lm)"},
            {"1715","houdini-lm(houdini-lm)"},
            {"1716","xmsg(xmsg)"},
            {"1717","fj-hdnet(fj-hdnet)"},
            {"1718","h323gatedisc(h323gatedisc)"},
            {"1719","h323gatestat(h323gatestat)"},
            {"1720","h323hostcall(h323hostcall)"},
            {"1721","caicci(caicci)"},
            {"1722","hks-lm(hks license manager)"},
            {"1723","pptp(pptp)"},
            {"1724","csbphonemaster(csbphonemaster)"},
            {"1725","iden-ralp(iden-ralp)"},
            {"1726","iberiagames(iberiagames)"},
            {"1727","winddx(winddx)"},
            {"1728","telindus(telindus)"},
            {"1729","citynl(citynl license management)"},
            {"1730","roketz(roketz)"},
            {"1731","msiccp(msiccp)"},
            {"1732","proxim(proxim)"},
            {"1733","sipat(sipat)"},
            {"1734","cambertx-lm(camber corporation license management)"},
            {"1735","privatechat(privatechat)"},
            {"1736","street-stream(street-stream)"},
            {"1737","ultimad(ultimad)"},
            {"1738","gamegen1(gamegen1)"},
            {"1739","webaccess(webaccess)"},
            {"1740","encore(encore)"},
            {"1741","cisco-net-mgmt(cisco-net-mgmt)"},
            {"1742","3com-nsd(3com-nsd)"},
            {"1743","cinegrfx-lm(cinema graphics license manager)"},
            {"1744","ncpm-ft(ncpm-ft)"},
            {"1745","remote-winsock(remote-winsock)"},
            {"1746","ftrapid-1(ftrapid-1)"},
            {"1747","ftrapid-2(ftrapid-2)"},
            {"1748","oracle-em1(oracle-em1)"},
            {"1749","aspen-services(aspen-services)"},
            {"1750","sslp(simple socket librarys portmaster)"},
            {"1751","swiftnet(swiftnet)"},
            {"1752","lofr-lm(leap of faith research license manager)"},
            {"1753","translogic-lm(translogic license manager)"},
            {"1754","oracle-em2(oracle-em2)"},
            {"1755","ms-streaming(ms-streaming)"},
            {"1756","capfast-lmd(capfast-lmd)"},
            {"1757","cnhrp(cnhrp)"},
            {"1758","tftp-mcast(tftp-mcast)"},
            {"1759","spss-lm(spss license manager)"},
            {"1760","www-ldap-gw(www-ldap-gw)"},
            {"1761","cft-0(cft-0)"},
            {"1762","cft-1(cft-1)"},
            {"1763","cft-2(cft-2)"},
            {"1764","cft-3(cft-3)"},
            {"1765","cft-4(cft-4)"},
            {"1766","cft-5(cft-5)"},
            {"1767","cft-6(cft-6)"},
            {"1768","cft-7(cft-7)"},
            {"1769","bmc-net-adm(bmc-net-adm)"},
            {"1770","bmc-net-svc(bmc-net-svc)"},
            {"1771","vaultbase(vaultbase)"},
            {"1772","essweb-gw(essweb gateway)"},
            {"1773","kmscontrol(kmscontrol)"},
            {"1774","global-dtserv(global-dtserv)"},
            {"1776","femis(federal emergency management information system)"},
            {"1777","powerguardian(powerguardian)"},
            {"1778","prodigy-internet(prodigy-internet)"},
            {"1779","pharmasoft(pharmasoft)"},
            {"1780","dpkeyserv(dpkeyserv)"},
            {"1781","answersoft-lm(answersoft-lm)"},
            {"1782","hp-hcip(hp-hcip)"},
            {"1783","fjris(fujitsu remote install service)"},
            {"1784","finle-lm(finle license manager)"},
            {"1785","windlm(wind river systems license manager)"},
            {"1786","funk-logger(funk-logger)"},
            {"1787","funk-license(funk-license)"},
            {"1788","psmond(psmond)"},
            {"1789","hello(hello)"},
            {"1790","nmsp(narrative media streaming protocol)"},
            {"1791","ea1(ea1)"},
            {"1792","ibm-dt-2(ibm-dt-2)"},
            {"1793","rsc-robot(rsc-robot)"},
            {"1794","cera-bcm(cera-bcm)"},
            {"1795","dpi-proxy(dpi-proxy)"},
            {"1796","vocaltec-admin(vocaltec server administration)"},
            {"1797","uma(uma)"},
            {"1798","etp(event transfer protocol)"},
            {"1799","netrisk(netrisk)"},
            {"1800","ansys-lm(ansys-license manager)"},
            {"1801","msmq(microsoft message que)"},
            {"1802","concomp1(concomp1)"},
            {"1803","hp-hcip-gwy(hp-hcip-gwy)"},
            {"1804","enl(enl)"},
            {"1805","enl-name(enl-name)"},
            {"1806","musiconline(musiconline)"},
            {"1807","fhsp(fujitsu hot standby protocol)"},
            {"1808","oracle-vp2(oracle-vp2)"},
            {"1809","oracle-vp1(oracle-vp1)"},
            {"1810","jerand-lm(jerand license manager)"},
            {"1811","scientia-sdb(scientia-sdb)"},
            {"1812","radius(radius)"},
            {"1813","radius-acct(radius accounting)"},
            {"1814","tdp-suite(tdp suite)"},
            {"1815","mmpft(mmpft)"},
            {"1818","etftp(enhanced trivial file transfer protocol)"},
            {"1819","plato-lm(plato license manager)"},
            {"1820","mcagent(mcagent)"},
            {"1821","donnyworld(donnyworld)"},
            {"1822","es-elmd(es-elmd)"},
            {"1823","unisys-lm(unisys natural language license manager)"},
            {"1824","metrics-pas(metrics-pas)"},
            {"1901","fjicl-tep-a(fujitsu icl terminal emulator program a)"},
            {"1902","fjicl-tep-b(fujitsu icl terminal emulator program b)"},
            {"1903","linkname(local link name resolution)"},
            {"1904","fjicl-tep-c(fujitsu icl terminal emulator program c)"},
            {"1905","sugp(secure up.link gateway protocol)"},
            {"1906","tpmd(tportmapperreq)"},
            {"1907","intrastar(intrastar)"},
            {"1908","dawn(dawn)"},
            {"1909","global-wlink(global world link)"},
            {"1911","mtp(starlight networks multimedia transport protocol)"},
            {"1912","(unassigned)"},
            {"1913","armadp(armadp)"},
            {"1914","elm-momentum(elm-momentum)"},
            {"1915","facelink(facelink)"},
            {"1916","persoft(persoft persona)"},
            {"1917","noagent(noagent)"},
            {"1918","can-nds(candle directory service - nds)"},
            {"1919","can-dch(candle directory service - dch)"},
            {"1920","can-ferret(candle directory service - ferret)"},
            {"1944","close-combat(close-combat)"},
            {"1945","dialogic-elmd(dialogic-elmd)"},
            {"1946","tekpls(tekpls)"},
            {"1947","hlserver(hlserver)"},
            {"1948","eye2eye(eye2eye)"},
            {"1949","ismaeasdaqlive(isma easdaq live)"},
            {"1950","ismaeasdaqtest(isma easdaq test)"},
            {"1951","bcs-lmserver(bcs-lmserver)"},
            {"1973","dlsrap(data link switching remote access protocol)"},
            {"1985","foliocorp(folio remote server)"},
            {"1986","licensedaemon(cisco license management)"},
            {"1987","tr-rsrb-p1(cisco rsrb priority 1 port)"},
            {"1988","tr-rsrb-p2(cisco rsrb priority 2 port)"},
            {"1989","tr-rsrb-p3(cisco rsrb priority 3 port)"},
            {"1990","stun-p1(cisco stun priority 1 port)"},
            {"1991","stun-p2(cisco stun priority 2 port)"},
            {"1992","stun-p3(cisco stun priority 3 port)"},
            {"1993","snmp-tcp-port(cisco snmp tcp port)"},
            {"1994","stun-port(cisco serial tunnel port)"},
            {"1995","perf-port(cisco perf port)"},
            {"1996","tr-rsrb-port(cisco remote srb port)"},
            {"1997","gdp-port(cisco gateway discovery protocol)"},
            {"1998","x25-svc-port(cisco x.25 service (xot))"},
            {"1999","tcp-id-port(cisco identification port)"},
            {"2001","dc"},
            {"2002","globe"},
            {"2004","mailbox"},
            {"2005","berknet"},
            {"2006","invokator"},
            {"2007","dectalk"},
            {"2008","conf"},
            {"2009","news(n)"},
            {"2010","search"},
            {"2011","raid-cc(raid)"},
            {"2012","ttyinfo"},
            {"2013","raid-am"},
            {"2014","troff"},
            {"2015","cypress"},
            {"2016","bootserver"},
            {"2017","cypress-stat"},
            {"2018","terminaldb"},
            {"2019","whosockami"},
            {"2020","xinupageserver"},
            {"2021","servexec"},
            {"2022","down"},
            {"2023","xinuexpansion3"},
            {"2024","xinuexpansion4"},
            {"2025","ellpack"},
            {"2026","scrabble"},
            {"2027","shadowserver"},
            {"2028","submitserver"},
            {"2030","device2"},
            {"2032","blackboard"},
            {"2033","glogger"},
            {"2034","scoremgr"},
            {"2035","imsldoc"},
            {"2038","objectmanager"},
            {"2040","lam"},
            {"2041","interbase"},
            {"2042","isis(isis)"},
            {"2043","isis-bcast(isis-bcast)"},
            {"2044","rimsl"},
            {"2045","cdfunc"},
            {"2046","sdfunc"},
            {"2047","dls"},
            {"2048","dls-monitor"},
            {"2049","shilp"},
            {"2065","dlsrpn(data link switch read port number)"},
            {"2067","dlswpn(data link switch write port number)"},
            {"2102","zephyr-srv(zephyr server)"},
            {"2103","zephyr-clt(zephyr serv-hm connection)"},
            {"2104","zephyr-hm(zephyr hostmanager)"},
            {"2105","minipay(minipay)"},
            {"2201","ats(advanced training system program)"},
            {"2202","imtc-map(int. multimedia teleconferencing cosortium)"},
            {"2213","kali(kali)"},
            {"2221","unreg-ab1(allen-bradley unregistered port)"},
            {"2222","unreg-ab2(allen-bradley unregistered port)"},
            {"2223","inreg-ab3(allen-bradley unregistered port)"},
            {"2232","ivs-video(ivs video default)"},
            {"2233","infocrypt(infocrypt)"},
            {"2234","directplay(directplay)"},
            {"2235","sercomm-wlink(sercomm-wlink)"},
            {"2236","nani(nani)"},
            {"2237","optech-port1-lm(optech port1 license manager)"},
            {"2238","aviva-sna(aviva sna server)"},
            {"2239","imagequery(image query)"},
            {"2241","ivsd(ivs daemon)"},
            {"2279","xmquery(xmquery)"},
            {"2280","lnvpoller(lnvpoller)"},
            {"2281","lnvconsole(lnvconsole)"},
            {"2282","lnvalarm(lnvalarm)"},
            {"2283","lnvstatus(lnvstatus)"},
            {"2284","lnvmaps(lnvmaps)"},
            {"2285","lnvmailmon(lnvmailmon)"},
            {"2286","nas-metering(nas-metering)"},
            {"2287","dna(dna)"},
            {"2288","netml(netml)"},
            {"2307","pehelp(pehelp)"},
            {"2401","cvspserver(cvspserver)"},
            {"2500","rtsserv(resource tracking system server)"},
            {"2501","rtsclient(resource tracking system client)"},
            {"2564","hp-3000-telnet(hp 3000 ns/vt block mode telnet)"},
            {"2592","netrek(netrek)"},
            {"2700","tqdata(tqdata)"},
            {"2784","www-dev(world wide web - development)"},
            {"2785","aic-np(aic-np)"},
            {"2786","aic-oncrpc(aic-oncrpc - destiny mcd database)"},
            {"2787","piccolo(piccolo - cornerstone software)"},
            {"2788","fryeserv(netware loadable module - seagate software)"},
            {"2789","media-agent(media agent)"},
            {"2908","mao(mao)"},
            {"2909","funk-dialout(funk dialout)"},
            {"2910","tdaccess(tdaccess)"},
            {"2911","blockade(blockade)"},
            {"2912","epicon(epicon)"},
            {"3000","hbci(hbci)"},
            {"3001","redwood-broker(redwood broker)"},
            {"3002","exlm-agent(exlm agent)"},
            {"3010","gw(telerate workstation)"},
            {"3011","trusted-web(trusted web)"},
            {"3047","hlserver(fast security hl server)"},
            {"3048","pctrader(sierra net pc trader)"},
            {"3049","nsws"},
            {"3141","vmodem(vmodem)"},
            {"3142","rdc-wh-eos(rdc wh eos)"},
            {"3143","seaview(sea view)"},
            {"3144","tarantella(tarantella)"},
            {"3145","csi-lfap(csi-lfap)"},
            {"3264","ccmail(cc:mail/lotus)"},
            {"3333","dec-notes(dec notes)"},
            {"3421","bmap(bull apprise portmapper)"},
            {"3454","mira(apple remote access protocol)"},
            {"3455","prsvp(rsvp port)"},
            {"3456","vat(vat default data)"},
            {"3457","vat-control(vat default control)"},
            {"3900","udt_os(unidata udt os)"},
            {"3984","mapper-nodemgr(mapper network node manager)"},
            {"3985","mapper-mapethd(mapper tcp/ip server)"},
            {"3986","mapper-ws_ethd(mapper workstation server)"},
            {"4008","netcheque(netcheque accounting)"},
            {"4009","chimera-hwm(chimera hwm)"},
            {"4132","nuts_dem(nuts daemon)"},
            {"4133","nuts_bootp(nuts bootp server)"},
            {"4134","nifty-hmi(nifty-serve hmi protocol)"},
            {"4321","rwhois(remote who is)"},
            {"4343","unicall(unicall)"},
            {"4444","krb524(krb524)"},
            {"4445","upnotifyp(upnotifyp)"},
            {"4446","n1-fwp(n1-fwp)"},
            {"4447","n1-rmgmt(n1-rmgmt)"},
            {"4448","asc-slmd(asc licence manager)"},
            {"4449","arcryptoip(arcrypto ip)"},
            {"4450","camp(camp)"},
            {"4451","ctisystemmsg(cti system msg)"},
            {"4452","ctiprogramload(cti program load)"},
            {"4453","nssalertmgr(nss alert manager)"},
            {"4454","nssagentmgr(nss agent manager)"},
            {"4500","sae-urn(sae-urn)"},
            {"4501","urn-x-cdchoice(urn-x-cdchoice)"},
            {"4672","rfa(remote file access server)"},
            {"5000","commplex-main"},
            {"5001","commplex-link"},
            {"5002","rfe(radio free ethernet)"},
            {"5003","claris-fmpro(claris filemaker pro)"},
            {"5004","avt-profile-1(avt-profile-1)"},
            {"5005","avt-profile-2(avt-profile-2)"},
            {"5010","telelpathstart(telepathstart)"},
            {"5011","telelpathattack(telepathattack)"},
            {"5020","zenginkyo-1(zenginkyo-1)"},
            {"5021","zenginkyo-2(zenginkyo-2)"},
            {"5050","mmcc(multimedia conference control tool)"},
            {"5145","rmonitor_secure"},
            {"5150","atmp(ascend tunnel management protocol)"},
            {"5190","aol(america-online)"},
            {"5191","aol-1(americaonline1)"},
            {"5192","aol-2(americaonline2)"},
            {"5193","aol-3(americaonline3)"},
            {"5236","padl2sim"},
            {"5300","hacl-hb(# ha cluster heartbeat)"},
            {"5301","hacl-gs(# ha cluster general services)"},
            {"5302","hacl-cfg(# ha cluster configuration)"},
            {"5303","hacl-probe(# ha cluster probing)"},
            {"5304","hacl-local(# ha cluster commands)"},
            {"5305","hacl-test(# ha cluster test)"},
            {"5400","excerpt(excerpt search)"},
            {"5401","excerpts(excerpt search secure)"},
            {"5555","personal-agent(personal agent)"},
            {"5631","pcanywheredata(pcanywheredata)"},
            {"5632","pcanywherestat(pcanywherestat)"},
            {"5678","rrac(remote replication agent connection)"},
            {"5679","dccm(direct cable connect manager)"},
            {"5713","proshareaudio(proshare conf audio)"},
            {"5714","prosharevideo(proshare conf video)"},
            {"5715","prosharedata(proshare conf data)"},
            {"5716","prosharerequest(proshare conf request)"},
            {"5717","prosharenotify(proshare conf notify)"},
            {"5729","openmail(openmail user agent layer)"},
            {"5745","fcopy-server(fcopy-server)"},
            {"5755","openmailg(openmail desk gateway server)"},
            {"5757","x500ms(openmail x.500 directory server)"},
            {"5766","openmailns(openmail newmail server)"},
            {"5767","s-openmail(openmail suer agent layer (secure))"},
            {"5800","vnc(virtual network computing server)"},
            {"5900","vnc(virtual network computing server)"},
            {"6000","x11(-6063 x window system)"},
            {"6110","softcm(hp softbench cm)"},
            {"6111","spc(hp softbench sub-process control)"},
            {"6112","dtspcd(dtspcd)"},
            {"6123","backup-express(backup express)"},
            {"6141","meta-corp(meta corporation license manager)"},
            {"6142","aspentec-lm(aspen technology license manager)"},
            {"6143","watershed-lm(watershed license manager)"},
            {"6144","statsci1-lm(statsci license manager - 1)"},
            {"6145","statsci2-lm(statsci license manager - 2)"},
            {"6146","lonewolf-lm(lone wolf systems license manager)"},
            {"6147","montage-lm(montage license manager)"},
            {"6148","ricardo-lm(ricardo north america license manager)"},
            {"6149","tal-pod(tal-pod)"},
            {"6253","crip(crip)"},
            {"6389","clariion-evr01(clariion-evr01)"},
            {"6455","skip-cert-recv(skip certificate receive)"},
            {"6456","skip-cert-send(skip certificate send)"},
            {"6558","xdsxdm"},
            {"6670","vocaltec-gold(vocaltec global online directory)"},
            {"6672","vision_server(vision_server)"},
            {"6673","vision_elmd(vision_elmd)"},
            {"6831","ambit-lm(ambit-lm)"},
            {"6969","acmsoda(acmsoda)"},
            {"7000","afs3-fileserver(file server itself)"},
            {"7001","afs3-callback(callbacks to cache managers)"},
            {"7002","afs3-prserver(users & groups database)"},
            {"7003","afs3-vlserver(volume location database)"},
            {"7004","afs3-kaserver(afs/kerberos authentication service)"},
            {"7005","afs3-volser(volume managment server)"},
            {"7006","afs3-errors(error interpretation service)"},
            {"7007","afs3-bos(basic overseer process)"},
            {"7008","afs3-update(server-to-server updater)"},
            {"7009","afs3-rmtsys(remote cache manager service)"},
            {"7010","ups-onlinet(onlinet uninterruptable power supplies)"},
            {"7099","lazy-ptop(lazy-ptop)"},
            {"7100","font-service(x font service)"},
            {"7121","virprot-lm(virtual prototypes license manager)"},
            {"7174","clutild(clutild)"},
            {"7200","fodms(fodms flip)"},
            {"7201","dlip(dlip)"},
            {"7395","winqedit(winqedit)"},
            {"7491","telops-lmd(telops-lmd)"},
            {"7511","pafec-lm(pafec-lm)"},
            {"7626","4444()"},
            {"7777","cbt(cbt)"},
            {"7781","accu-lmgr(accu-lmgr)"},
            {"7999","irdmi2(irdmi2)"},
            {"8000","irdmi(irdmi/shoutcast server)"},
            {"8010","wingate-logfile(wingate web logfile)"},
            {"8032","pro-ed(proed)"},
            {"8080","www-proxy(standard http proxy)"},
            {"8450","npmp(npmp)"},
            {"8888","ddi-tcp-1(newsedge server tcp (tcp 1))"},
            {"8889","ddi-tcp-2(desktop data tcp 1)"},
            {"8890","ddi-tcp-3(desktop data tcp 2)"},
            {"8891","ddi-tcp-4(desktop data tcp 3: ness application)"},
            {"8892","ddi-tcp-5(desktop data tcp 4: farm product)"},
            {"8893","ddi-tcp-6(desktop data tcp 5: newsedge/web application)"},
            {"8894","ddi-tcp-7(desktop data tcp 6: coal application)"},
            {"9000","cslistener(cslistener)"},
            {"9100","jetdirect(hp jetdirect printer server)"},
            {"9535","man"},
            {"9876","sd(session director)"},
            {"9992","palace(palace)"},
            {"9993","palace(palace)"},
            {"9994","palace(palace)"},
            {"9995","palace(palace)"},
            {"9996","palace(palace)"},
            {"9997","palace(palace)"},
            {"9998","distinct32(distinct32)"},
            {"9999","distinct(distinct)"},
            {"10000","ndmp(network data management protocol)"},
            {"12345","netbus(win95/nt netbus backdoor)"},
            {"12753","tsaf(tsaf port)"},
            {"17007","isode-dua"},
            {"18000","biimenu(beckman instruments)"},
            {"21845","webphone(webphone)"},
            {"21846","netspeak-is(netspeak corp. directory services)"},
            {"21847","netspeak-cs(netspeak corp. connection services)"},
            {"21848","netspeak-acd(netspeak corp. automatic call distribution)"},
            {"21849","netspeak-cps(netspeak corp. credit processing system)"},
            {"22273","wnn6(wnn6)"},
            {"22555","vocaltec-wconf(vocaltec web conference)"},
            {"22800","aws-brf(telerate information platform lan)"},
            {"22951","brf-gw(telerate information platform wan)"},
            {"25000","icl-twobase1(icl-twobase1)"},
            {"25001","icl-twobase2(icl-twobase2)"},
            {"25002","icl-twobase3(icl-twobase3)"},
            {"25003","icl-twobase4(icl-twobase4)"},
            {"25004","icl-twobase5(icl-twobase5)"},
            {"25005","icl-twobase6(icl-twobase6)"},
            {"25006","icl-twobase7(icl-twobase7)"},
            {"25007","icl-twobase8(icl-twobase8)"},
            {"25008","icl-twobase9(icl-twobase9)"},
            {"25009","icl-twobase10(icl-twobase10)"},
            {"25793","vocaltec-hos(vocaltec address server)"},
            {"25867","webcam32(webcam32 admin)"},
            {"26000","quake(quake)"},
            {"26208","wnn6-ds(wnn6-ds)"},
            {"47557","dbbrowse(databeam corporation)"},
            {"47806","ap(alc protocol)"},
            {"47808","bacnet(building automation and control networks)"}
        };

        /// <summary>UDP端口对应服务名称</summary>>
        public static readonly string[,] UdpPortName = {
            {"1","Sockets des Troie"},
            {"9","Chargen"},
            {"19","Chargen"},
            {"69","Pasana"},
            {"80","Penrox"},
            {"371","ClearCase版本管理软件"},
            {"445","公共Internet文件系统(CIFS)"},
            {"500","Internet密钥交换"},
            {"1025","Maverick's Matrix 1.2 - 2.0"},
            {"1026","Remote Explorer 2000"},
            {"1027","UC聊天软件,Trojan.Huigezi.e"},
            {"1028","3721上网助手(用途不明,建议用户警惕!),KiLo,SubSARI"},
            {"1029","SubSARI"},
            {"1031","Xot"},
            {"1032","Akosch4"},
            {"1104","RexxRave"},
            {"1111","Daodan"},
            {"1116","Lurker"},
            {"1122","Last 2000,Singularity"},
            {"1183","Cyn,SweetHeart"},
            {"1200","NoBackO"},
            {"1201","NoBackO"},
            {"1342","BLA trojan"},
            {"1344","Ptakks"},
            {"1349","BO dll"},
            {"1561","MuSka52"},
            {"1772","NetControle"},
            {"1978","Slapper"},
            {"1985","Black Diver"},
            {"2000","A-trojan,Fear,Force,GOTHIC Intruder,Last 2000,Real 2000"},
            {"2001","Scalper"},
            {"2002","Slapper"},
            {"2015","raid-cs"},
            {"2018","rellpack"},
            {"2130","Mini BackLash"},
            {"2140","Deep Throat,Foreplay,The Invasor"},
            {"2222","SweetHeart, Way"},
            {"2339","Voice Spy"},
            {"2702","Black Diver"},
            {"2989","RAT"},
            {"3150","Deep Throat"},
            {"3215","XHX"},
            {"3333","Daodan"},
            {"3801","Eclypse"},
            {"3996","Remote Anything"},
            {"4128","RedShad"},
            {"4156","Slapper"},
            {"4500","sae-urn"},
            {"5419","DarkSky"},
            {"5503","Remote Shell Trojan"},
            {"5555","Daodan"},
            {"5882","Y3K RAT"},
            {"5888","Y3K RAT"},
            {"6112","Battle.net Game"},
            {"6666","KiLo"},
            {"6667","KiLo"},
            {"6766","KiLo"},
            {"6767","KiLo,UandMe"},
            {"6838","Mstream Agent-handler"},
            {"7028","未知木马"},
            {"7424","Host Control"},
            {"7788","Singularity"},
            {"7983","MStream handler-agent"},
            {"8012","Ptakks"},
            {"8090","Aphex's Remote Packet Sniffer"},
            {"8127","9_119,Chonker"},
            {"8488","KiLo"},
            {"8489","KiLo"},
            {"8787","BackOrifice 2000"},
            {"8879","BackOrifice 2000"},
            {"9325","MStream Agent-handler"},
            {"10000","XHX"},
            {"10067","Portal of Doom"},
            {"10084","Syphillis"},
            {"10100","Slapper"},
            {"10167","Portal of Doom"},
            {"10498","Mstream"},
            {"10666","Ambush"},
            {"11225","Cyn"},
            {"12321","Protoss"},
            {"12345","BlueIce 2000"},
            {"12378","W32/Gibe@MM"},
            {"12623","ButtMan,DUN Control"},
            {"15210","UDP remote shell backdoor server"},
            {"15486","KiLo"},
            {"16514","KiLo"},
            {"16515","KiLo"},
            {"18753","Shaft handler to Agent"},
            {"20433","Shaft"},
            {"21554","GirlFriend"},
            {"22784","Backdoor.Intruzzo"},
            {"23476","Donald Dick"},
            {"25123","MOTD"},
            {"26274","Delta Source"},
            {"26374","Sub-7 2.1"},
            {"26444","Trin00/TFN2K"},
            {"26573","Sub-7 2.1"},
            {"27184","Alvgus trojan 2000"},
            {"27444","Trinoo"},
            {"29589","KiLo"},
            {"29891","The Unexplained"},
            {"30103","NetSphere"},
            {"31320","Little Witch"},
            {"31335","Trin00 DoS Attack"},
            {"31337","Baron Night, BO client, BO2, Bo Facil, BackFire, Back Orifice, DeepBO"},
            {"31338","Back Orifice, NetSpy DK, DeepBO"},
            {"31339","Little Witch"},
            {"31340","Little Witch"},
            {"31416","Lithium"},
            {"31787","Hack aTack"},
            {"31789","Hack aTack"},
            {"31790","Hack aTack"},
            {"31791","Hack aTack"},
            {"33390","未知木马"},
            {"34555","Trinoo"},
            {"35555","Trinoo"},
            {"43720","KiLo"},
            {"44014","Iani"},
            {"44767","School Bus"},
            {"46666","Taskman"},
            {"47262","Delta Source"},
            {"47785","KiLo"},
            {"49301","OnLine keyLogger"},
            {"49683","Fenster"},
            {"49698","KiLo"},
            {"52901","Omega"},
            {"54320","Back Orifice"},
            {"54321","Back Orifice 2000"},
            {"54341","NetRaider Trojan"},
            {"61746","KiLO"},
            {"61747","KiLO"},
            {"61748","KiLO"},
            {"65432","The Traitor"}
        };
    }
}
