// Assembly MWArray, Version 2.12.0.0

[assembly: System.Reflection.AssemblyVersion("2.12.0.0")]
[assembly: System.Reflection.AssemblyCompany("The MathWorks, Inc.")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2001-2011")]
[assembly: System.Reflection.AssemblyTrademark("The MathWorks, Inc.")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyProduct("MATLAB Builder NE")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyTitle("MathWorks, .NET MWArray API")]
[assembly: System.Runtime.InteropServices.Guid("a98077d9-f76f-44bd-b67e-3477ccd32562")]
[assembly: System.Reflection.AssemblyFileVersion("2.12.0.0")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyDescription("MATLAB array wrapper classes for .NET")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: MathWorks.MATLAB.NET.Utility.MCRVersion("7", "17", "")]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1)] 
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]
